export interface IOrganization {
  id: number;
  external_id: string;
  account_id: number;
  name: string;
  cnpj: string;
  state: string;
  state_code: number;
  zip_code: string;
  neighborhood: string;
  number: string;
  street: string;
  complement: string | null;
  city: string;
  city_code: string;
  average_withdrawal_term: number;
  average_withdrawal_price: number;
  created_at: string;
  updated_at: string;
  company_name: string;
  emites_id: number;
  state_registration: string;
  tax_regime: string;
  kind: string;
  serie_nfe: string;
  latitude: string;
  longitude: string;
  parent_id: number | null;
  delivery_radius_max: string;
  minimum_time_order_return: number;
  additional_nfe_fiscal_info: string;
  additional_nfe_info: string | null;
  coupons_expire_days: number;
  active: boolean;
  use_average_cost: boolean;
  auto_invoice: boolean;
  auto_generate_label: boolean;
  show_delivery_address_on_nfe: boolean;
  use_delivery_address_as_recipient_in_nfe: boolean;
  use_discount_in_the_average_cost: boolean;
  use_icms_in_the_average_cost: boolean;
  use_freight_value_in_the_average_cost: boolean;
  issue_invoice_with_cost_price_for_gift: boolean;
  customer_aquisition_channels: string[];
}
